### ISSUE TITLE
Help Wanted !!

### ISSUE THREAD

**Issue by htr-tech** [Sazxt/comz#1]

**Comment by erwincatt** [comment]
> ### Dear @Sazxt ,
> #### First of all take gratitude for building such a tool .  But unfortunately i have encrypted a tool with comz but I have lost the original source code of that tool . 
> #### I really need to decrypt it .
> ### So please make a decoder script script or tell how to decrypt it .

Lmao retard

**Comment by erwincatt** [comment]
@htr-tech 
Use https://github.com/erwincatt/hackingtool

It have option to decrypt your script.

**Comment by htr-tech** [comment]
> @htr-tech
> Use https://github.com/erwincatt/hackingtool
> 
> It have option to decrypt your script.

please tell clearly & how to use this tool ???

**Comment by erwincatt** [comment]
> _No description provided._

You shouldn't remove your issue
https://archive.is/f3koK

**Comment by erwincatt** [comment]
@htr-tech also anyone can check old one in edits :)
![IMG_20200509_155624](https://user-images.githubusercontent.com/62641404/81471288-ad6c2f80-920d-11ea-9c0d-ffe992d0791e.jpg)

**Comment by erwincatt** [comment]
Also you asked how to use this tool @htr-tech and then deleted your comment.

![IMG_20200509_160826_945](https://user-images.githubusercontent.com/62641404/81471548-8282db00-920f-11ea-9ce8-88e72cbfeafa.jpg)

Don't be shy. If you wanna know how to use it them don't hesitate to ask. I like to help everyone.

**Comment by Cvar1984** [comment]
Mega retard, lmao

**Comment by robbyoconnor** [comment]
![image](https://user-images.githubusercontent.com/23088/81488514-a4905380-9237-11ea-81a6-6784d7a0a956.png)

Nice try to cover your tracks but you can't do that.
